import type { Knex } from 'knex'

export async function legacyMigration_3_4_27_0(knex: Knex) {
  await knex.raw(`
    ALTER PROCEDURE [dbo].[P_SEND_PROG_TO_ACTIVITY] @IN_MACHINEID INT, @IN_PRGNO INT
    AS
    DECLARE @MAX_VERSION INT;
    DECLARE @MY_TIME timestamp;
    SELECT @MY_TIME = CAST ( GETDATE() AS TIMESTAMP);
    SELECT @MAX_VERSION = -1;
    SELECT @MAX_VERSION = (SELECT MAX(MACHINEPRGVERSIONNO)  FROM BAMASTERPRGHEADER WHERE MACHINEID= @IN_MACHINEID AND PROGNO = @IN_PRGNO);
    IF @MAX_VERSION IS NULL
    SET @MAX_VERSION = 0;
    UPDATE BAMASTERPRGHEADER SET RELEASEENDDATE= @MY_TIME WHERE ( MACHINEID= @IN_MACHINEID AND MACHINEPRGVERSIONNO= @MAX_VERSION AND PROGNO= @IN_PRGNO );
    SET @MAX_VERSION = @MAX_VERSION + 1;
    INSERT INTO BAMASTERPRGHEADER
    SELECT @IN_MACHINEID, @MAX_VERSION, @MY_TIME, NULL, @IN_PRGNO, PROCESSCODE, NAME, DURATION, TOTALSTEP, CHANGEDATE, TBBCHANGESOURCE, TBBCHANGEDATE,
    CREATIONDATE, USERCOMMENT, Null as USERNAME, Null as CHANGETIME, Null as WHATCHANGE, 0 as PRGSOURCE, TotalChemReq, TotalDyeReq,ManChemReq,AutoChemReq,
    AutoDyeReq,ManDyeReq,DefaultRecipeNo,ICONNAME,ORDEROFREQUESTS,TOTALSALTREQ,TOTALGM1REQ,TOTALGM2REQ,PHASEVERSION, INTERVENTIONFREEPROGRAM, ADDITIONALPROCESSCODE
    FROM BFMASTERPRGHEADER WHERE MACHINEID = @IN_MACHINEID AND PROGNO = @IN_PRGNO;
    INSERT INTO BAMASTERSTEPS
    SELECT @IN_MACHINEID, @MAX_VERSION, @IN_PRGNO, MAINSTEP, PARALELSTEP, COMMANDNO, ISCONDITIONAL, CONDITIONSTR, THEORETICDURATION
    FROM BFMASTERSTEPS WHERE MACHINEID = @IN_MACHINEID AND PROGNO = @IN_PRGNO;
    INSERT INTO BAMASTERSTEPPARAMS
    SELECT @IN_MACHINEID, @MAX_VERSION, @IN_PRGNO, MAINSTEP, PARALELSTEP, PARAMETERINDEX, VALUE, CONTAINSVARIABLE, ERRORWARNING, OPTIMIZED
    FROM BFMASTERSTEPPARAMS WHERE MACHINEID = @IN_MACHINEID AND PROGNO = @IN_PRGNO ;
    INSERT INTO BAMASTERSTEPINPUTOUTPUTS
    SELECT @IN_MACHINEID, @MAX_VERSION, @IN_PRGNO, MAINSTEP, PARALELSTEP, IOINDEX, IOID, IOTYPE
    FROM BFMASTERSTEPINPUTOUTPUTS WHERE MACHINEID = @IN_MACHINEID AND PROGNO = @IN_PRGNO;
    INSERT INTO BAMASTERSTEPSELECTIONLIST
    SELECT @IN_MACHINEID, @MAX_VERSION, SELECTIONINDEX, @IN_PRGNO, MAINSTEP, PARALELSTEP, IOINDEX, SELECTEDIOID, IOTYPE
    FROM BFMASTERSTEPSELECTIONLIST WHERE MACHINEID = @IN_MACHINEID AND PROGNO = @IN_PRGNO;
    INSERT INTO BAMASTERPRGVARIABLEVALUES
    SELECT @IN_MACHINEID, @MAX_VERSION, @IN_PRGNO, VARIABLEID, VALUE
    FROM BFMASTERPRGVARIABLEVALUES WHERE MACHINEID = @IN_MACHINEID AND PROGNO = @IN_PRGNO ;
  `);
}
