import type { Knex } from 'knex'

export async function legacyMigration_3_4_15_0(_knex: Knex) {
  // These are handled by 000_init-database.sql migration.
  // Keeping this here just for reference. No actual schema changes are needed for this version.

  // await knex.raw(`DROP TABLE BAMACHBATCHPARAMETERS`)

  // await knex.raw(`
  //   CREATE TABLE [BAMACHBATCHPARAMETERS](
  //   [BATCHPARAMETERID] [int] NOT NULL,
  //   [MACHINEID] [int] NOT NULL,
  //   MACHINECOMMANDSETNO int NOT NULL,
  //   [PARAMSTRING] [nvarchar](50) NULL,
  //   [PARAMLOWLIMIT] [real] NOT NULL,
  //   [PARAMHIGHLIMIT] [real] NOT NULL,
  //   [BATCHPLANNING] [bit] NOT NULL,
  //   [BATCHSTART] [bit] NOT NULL,
  //   [RECIPE] [bit] NOT NULL,
  //   [DEFAULTVALUE] [real] NULL,
  //   [PARAMETERTYPE] [tinyint] NULL,
  //   [SELECTIONLIST] [varchar](1023) NOT NULL,
  //   [UNITCODE] [tinyint] NULL,
  //   [SELECTIONVALUES] [varchar](1023) NOT NULL,
  //   [ISDELETED] [bit] NOT NULL,
  //   [TBBCHANGETIME] [datetime] NULL,
  //   [CHANGETIME] [datetime] NULL,
  //   [FORMAT] [tinyint] NULL,
  //   [PARAMETERID] [tinyint] NULL,
  //   [UNITTEXT] [nvarchar](20) NULL,
  //   [PARAMSTRINGEn] [nvarchar](50) NOT NULL,
  //   [SELECTIONLISTDEFAULT] [nvarchar](25) NULL,
  //   CONSTRAINT [PK_BAMACHBATCHPARAMETERS] PRIMARY KEY CLUSTERED ([BATCHPARAMETERID] ASC,[MACHINEID] ASC,MACHINECOMMANDSETNO ASC) ON [PRIMARY]) ON [PRIMARY];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHBATCHPARAMETERS_PARAMLOWLIMIT]  DEFAULT ((0)) FOR [PARAMLOWLIMIT];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHBATCHPARAMETERS_PARAMHIGHLIMIT]  DEFAULT ((0)) FOR [PARAMHIGHLIMIT];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHBATCHPARAMETERS_BATCHPLANNING]  DEFAULT ((0)) FOR [BATCHPLANNING];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHBATCHPARAMETERS_BATCHSTART]  DEFAULT ((1)) FOR [BATCHSTART];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHBATCHPARAMETERS_RECIPE]  DEFAULT ((0)) FOR [RECIPE];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHBATCHPARAMETERS_DEFAULTVALUE]  DEFAULT ((0)) FOR [DEFAULTVALUE];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHBATCHPARAMETERS_PARAMETERTYPE]  DEFAULT ((1)) FOR [PARAMETERTYPE];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHBATCHPARAMETERS_SELECTIONLIST]  DEFAULT ('YOK') FOR [SELECTIONLIST];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHBATCHPARAMETERS_UNITCODE]  DEFAULT ((0)) FOR [UNITCODE];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHBATCHPARAMETERS_SELECTIONVALUES]  DEFAULT ('YOK') FOR [SELECTIONVALUES];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHBATCHPARAMETERS_ISDELETED]  DEFAULT ((0)) FOR [ISDELETED];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  DEFAULT ((0)) FOR [FORMAT];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  DEFAULT ((0)) FOR [PARAMETERID];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] ADD  DEFAULT ('') FOR [PARAMSTRINGEn];
  //   ALTER TABLE [BAMACHBATCHPARAMETERS]  WITH CHECK ADD  CONSTRAINT [FK_BAMACHBATCHPARAMETERS_BFMACHINES] FOREIGN KEY([MACHINEID]) REFERENCES [BFMACHINES] ([MACHINEID]) ON UPDATE CASCADE ON DELETE CASCADE;
  //   ALTER TABLE [BAMACHBATCHPARAMETERS] CHECK CONSTRAINT [FK_BAMACHBATCHPARAMETERS_BFMACHINES];
  // `)

  // await knex.raw(`DROP TABLE BAMACHPARAMETERS`)

  // await knex.raw(`
  //   CREATE TABLE [dbo].[BAMACHPARAMETERS](
  //   [MACHINEPARAMETERID] [int] NOT NULL,
  //   [MACHINEID] [int] NOT NULL,
  //   MACHINECOMMANDSETNO int NOT NULL,
  //   [PARAMSTRING] [nvarchar](50) NULL,
  //   [PARAMLOWLIMIT] [real] NOT NULL,
  //   [PARAMHIGHLIMIT] [real] NOT NULL,
  //   [PARAMETERTYPE] [int] NOT NULL,
  //   [SELECTIONLIST] [varchar](1023) NOT NULL,
  //   [UNITCODE] [int] NOT NULL,
  //   [SELECTIONVALUES] [varchar](1023) NOT NULL,
  //   [ISDELETED] [bit] NOT NULL,
  //   [TBBCHANGETIME] [datetime] NULL,
  //   [CHANGETIME] [datetime] NULL,
  //   [DEFAULTVALUE] [real] NULL,
  //   [dmArea] [int] NULL,
  //   [consScreen] [int] NULL,
  //   [consFormat] [int] NULL,
  //   [consUnit] [int] NULL,
  //   [currentValue] [real] NULL,
  //   CONSTRAINT [PK_BAMACHPARAMETERS] PRIMARY KEY CLUSTERED ([MACHINEPARAMETERID] ASC,[MACHINEID] ASC,MACHINECOMMANDSETNO ASC) ON [PRIMARY]) ON [PRIMARY];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHPARAMETERS_PARAMLOWLIMIT]  DEFAULT ((0)) FOR [PARAMLOWLIMIT];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHPARAMETERS_PARAMHIGHLIMIT]  DEFAULT ((0)) FOR [PARAMHIGHLIMIT];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHPARAMETERS_PARAMETERTYPE]  DEFAULT ((1)) FOR [PARAMETERTYPE];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHPARAMETERS_SELECTIONLIST]  DEFAULT ('YOK') FOR [SELECTIONLIST];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHPARAMETERS_UNITCODE]  DEFAULT ((1)) FOR [UNITCODE];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHPARAMETERS_SELECTIONVALUES]  DEFAULT ('YOK') FOR [SELECTIONVALUES];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] ADD  CONSTRAINT [DF_BAMACHPARAMETERS_ISDELETED]  DEFAULT ((0)) FOR [ISDELETED];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] ADD  DEFAULT ((0)) FOR [DEFAULTVALUE];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] ADD  DEFAULT ((0)) FOR [dmArea];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] ADD  DEFAULT ((0)) FOR [consScreen];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] ADD  DEFAULT ((0)) FOR [consFormat];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] ADD  DEFAULT ((0)) FOR [consUnit];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] ADD  DEFAULT ((0)) FOR [currentValue];
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS]  WITH CHECK ADD  CONSTRAINT [FK_BAMACHPARAMETERS_BFMACHINES] FOREIGN KEY([MACHINEID])REFERENCES [dbo].[BFMACHINES] ([MACHINEID]) ON UPDATE CASCADE ON DELETE CASCADE;
  //   ALTER TABLE [dbo].[BAMACHPARAMETERS] CHECK CONSTRAINT [FK_BAMACHPARAMETERS_BFMACHINES];
  // `)

  // await knex.raw(`
  //   CREATE TABLE [BACOMMANDFORMULAS](
  //   [machineId] [int] NOT NULL,
  //   [formulaId] [int] NOT NULL,
  //   machineCommandSetNo int NOT NULL,
  //   [formula] [nvarchar](400) NOT NULL,
  //   [commandNo] [int] NULL,
  //   [commandParameterNo] [int] NULL,
  //   [formulaName] [nvarchar](255) NULL,
  //   CONSTRAINT [PK_BACOMMANDFORMULAS] PRIMARY KEY CLUSTERED
  //   ([machineId] ASC,[formulaId] ASC, machineCommandSetNo ASC)ON [PRIMARY]) ON [PRIMARY];
  //   ALTER TABLE [BACOMMANDFORMULAS] ADD  DEFAULT ((0)) FOR [commandNo];
  //   ALTER TABLE [BACOMMANDFORMULAS] ADD  DEFAULT ((-1)) FOR [commandParameterNo];
  //   ALTER TABLE [BACOMMANDFORMULAS]  WITH CHECK ADD  CONSTRAINT [FK_BACOMMANDFORMULAS_BFMACHINES] FOREIGN KEY([machineId]) REFERENCES [BFMACHINES] ([MACHINEID]) ON UPDATE CASCADE ON DELETE CASCADE;
  //   ALTER TABLE [BACOMMANDFORMULAS] CHECK CONSTRAINT [FK_BACOMMANDFORMULAS_BFMACHINES];
  // `)
}
