import type { Knex } from 'knex'

export async function legacyMigration_3_4_16_0(_knex: Knex) {
  // These are handled by 000_init-database.sql migration.
  // Keeping this here just for reference. No actual schema changes are needed for this version.

  // await knex.raw(`
  //   CREATE TABLE BADATA_OPTIMIZEDPROGRAMDURATIONS_BEFORESTART(
  //   REQUESTEDJOBORDER NVARCHAR(15),
  //   MACHINEID int,
  //   PROGINDEX tinyint,
  //   PROGNO int,
  //   OPTIMIZEDDURATION int)
  // `)

  // await knex.raw(`
  //   CREATE TABLE BADATA_OPTIMIZEDCOMMANDDURATIONS_BEFORESTART(
  //   REQUESTEDJOBORDER NVARCHAR(15),
  //   MACHINEID int,
  //   PROGINDEX tinyint,
  //   PROGNO int,
  //   MAINSTEP smallint,
  //   PARALELSTEP smallint,
  //   COMMANDNO smallint,
  //   PARAMETERINDEX tinyint,
  //   OPTIMIZEDDURATION int,
  //   OPTIMIZEDVALUE VARCHAR(31),
  //   OPTIMIZEDVALUESOURCE tinyint)
  // `)

  // await knex.raw(`
  //   CREATE TABLE BADATA_OPTIMIZEDPROGRAMDURATIONS(
  //   ID INT IDENTITY(1,1),
  //   BATCHKEY int NOT NULL,
  //   PROGINDEX tinyint,
  //   PROGNO int,
  //   OPTIMIZEDDURATION int,
  //   CONSTRAINT PK_BADATA_OPTIMIZEDPROGRAMDURATIONS PRIMARY KEY NONCLUSTERED (ID ASC),
  //   INDEX IND_BADATA_BADATA_OPTIMIZEDPROGRAMDURATIONS_BATCHKEY CLUSTERED (BATCHKEY),
  //   CONSTRAINT FK_BADATA_OPTIMIZEDPROGRAMDURATIONS_BADATA Foreign key (BATCHKEY) references BADATA (BATCHKEY) ON DELETE CASCADE ON UPDATE CASCADE )
  // `)

  // await knex.raw(`
  //   CREATE TABLE BADATA_OPTIMIZEDCOMMANDDURATIONS(
  //   ID INT IDENTITY(1,1),
  //   BATCHKEY int NOT NULL,
  //   PROGINDEX tinyint NOT NULL,
  //   PROGNO int NOT NULL,
  //   MAINSTEP smallint NOT NULL,
  //   PARALELSTEP smallint NOT NULL,
  //   COMMANDNO smallint NOT NULL,
  //   PARAMETERINDEX tinyint NOT NULL,
  //   OPTIMIZEDDURATION int NOT NULL,
  //   OPTIMIZEDVALUE VARCHAR(31) NOT NULL,
  //   OPTIMIZEDVALUESOURCE tinyint NOT NULL,
  //   CONSTRAINT PK_BADATA_OPTIMIZEDVALUES PRIMARY KEY NONCLUSTERED (ID ASC),
  //   INDEX IND_BADATA_BADATA_OPTIMIZEDCOMMANDDURATIONS_BATCHKEY CLUSTERED (BATCHKEY),
  //   CONSTRAINT FK_BADATA_OPTIMIZEDCOMMANDDURATIONS_BADATA Foreign key (BATCHKEY) references BADATA (BATCHKEY) ON DELETE CASCADE ON UPDATE CASCADE )
  // `)
}
