import type { Knex } from 'knex'

export async function legacyMigration_3_4_26_0(knex: Knex) {
  if (!await knex.schema.hasColumn('BACOMMANDPARAMETERS', 'MACHINECONSTANTFORLOWLIMIT')) {
    await knex.raw('ALTER TABLE BACOMMANDPARAMETERS ADD MACHINECONSTANTFORLOWLIMIT int not null default -1 ')
    await knex.raw('UPDATE BACOMMANDPARAMETERS SET MACHINECONSTANTFORLOWLIMIT = -1')
  }

  if (!await knex.schema.hasColumn('BACOMMANDPARAMETERS', 'MACHINECONSTANTFORHIGHLIMIT')) {
    await knex.raw('ALTER TABLE BACOMMANDPARAMETERS ADD MACHINECONSTANTFORHIGHLIMIT int not null default -1 ')
    await knex.raw('UPDATE BACOMMANDPARAMETERS SET MACHINECONSTANTFORHIGHLIMIT = -1')
  }

  if (!await knex.schema.hasColumn('BAMACHBATCHPARAMETERS', 'MACHINECONSTANTFORLOWLIMIT')) {
    await knex.raw('ALTER TABLE BAMACHBATCHPARAMETERS ADD MACHINECONSTANTFORLOWLIMIT int not null default -1 ')
    await knex.raw('UPDATE BAMACHBATCHPARAMETERS SET MACHINECONSTANTFORLOWLIMIT = -1')
  }

  if (!await knex.schema.hasColumn('BAMACHBATCHPARAMETERS', 'MACHINECONSTANTFORHIGHLIMIT')) {
    await knex.raw('ALTER TABLE BAMACHBATCHPARAMETERS ADD MACHINECONSTANTFORHIGHLIMIT int not null default -1 ')
    await knex.raw('UPDATE BAMACHBATCHPARAMETERS SET MACHINECONSTANTFORHIGHLIMIT = -1')
  }

  if (!await knex.schema.hasColumn('BAMACHBATCHPARAMETERS', 'VISIBILITY')) {
    await knex.raw('ALTER TABLE BAMACHBATCHPARAMETERS ADD VISIBILITY bit not null default 1 ')
    await knex.raw('UPDATE BAMACHBATCHPARAMETERS SET VISIBILITY = 1')
  }
}
