export const TeleskopSettings = {
  UserManagentActive: 1,
  PhaseModeActive: 2,
  CustomErpPrmOptimization: 3,
  AllowedCharsForJobOrder: 4,
  RecipeEnterActive: 5,
  TimeBasedModeActive: 6,
  DyehouseNumber: 7,
  ProcessUsageActive: 8,
  SaveIOValuesInDatabase: 9,
  StoreRequestsInDatabase: 10,
  CommandOptimisationParameterCount: 11,
  EditorSelectedCommandIcons: 12,
  InitialWaterTemperature: 13,
  IntegrationDatabaseActive: 14,
  IntegrationDatabaseConnectionString: 15,
  JoborderBarcodeType: 16,
  PhaseBigIconsEnabled: 17,
  PhaseSmallIconsVisible: 18,
} as const
