stages:
  - prepare
  - release
  - deploy

.docker-prepare: &docker-prepare
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker context create gitlab-context
  - docker buildx create --name gitlab-builder --driver docker-container --use gitlab-context
  - docker buildx inspect --bootstrap

.prepare-ssh: &prepare-ssh
  # Install ssh-agent
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  # Run ssh-agent
  - eval $(ssh-agent -s)
  # # Give the right permissions, otherwise ssh-add will refuse to add files
  # # Add the SSH key stored in SSH_PRIVATE_KEY file type CI/CD variable to the agent store
  - chmod 400 "$SSH_PRIVATE_KEY"
  - ssh-add "$SSH_PRIVATE_KEY"
  # # Create the SSH directory and give it the right permissions
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # # Copy known hosts file to SSH directory
  - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

.app-rules:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc\.\d+)?$/
      variables:
        CACHE_COMPILE_FROM: ${CI_DEFAULT_BRANCH_SLUG}
        CACHE_COMPILE_TO: ${CI_DEFAULT_BRANCH_SLUG}
    - if: $CI_COMMIT_BRANCH == "dev"
      variables:
        CACHE_COMPILE_FROM: dev
        CACHE_COMPILE_TO: dev

.hotfix-rules:
  rules:
    - if: $CI_COMMIT_TAG =~ /^[a-z._-]+@\d+\.\d+\.\d+-hotfix\d+$/

.devops-rules:
  rules:
    - if: $CI_COMMIT_TAG =~ /^devops@/

.merge-request-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

# Instance level authentication, sets global `.npmrc`
.npm-registry-global-auth: &npm-registry-global-auth
  - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/packages/npm/" >> $(npm config get userconfig)
  - echo "${CI_API_V4_URL#http*:}/packages/npm/:_authToken=\${CI_JOB_TOKEN}" >> $(npm config get userconfig)

# Instance level authentication, sets `.npmrc` at current directory
.npm-registry-local-auth: &npm-registry-local-auth
  - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/packages/npm/" >> .npmrc
  - echo "${CI_API_V4_URL#http*:}/packages/npm/:_authToken=\${CI_JOB_TOKEN}" >> .npmrc

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

variables:
  TARGET_APPS:
    # value: archive recipes dispensing-manager-ui communication-driver machine-status machines migration-service multi-monitor planning-board planning-board-engine root websockify program-editor
    value: archive 
    description: Whitespace seperated list of apps to build/release

prepare-apps:
  image: node:22
  stage: prepare
  extends:
    - .app-rules
  before_script: 
    - npm install -g turbo@^2
  script:
    # - export TARGET_APPS="$(node ./scripts/detect-file-change.js)"
    # - echo "TARGET_APPS=$TARGET_APPS" > changed-apps.env
    - |
      for APP_NAME in $TARGET_APPS; do
        turbo prune --scope=$APP_NAME --out-dir out-$APP_NAME --docker
      done
  artifacts:
    expire_in: 1 hour
    paths:
      - out-*/
    reports:
      dotenv: changed-apps.env

prepare-hotfix:
  image: node:22
  stage: prepare
  extends:
    - .hotfix-rules
  script:
    - npm install -g turbo@^2
    - export APP_NAME=$(echo $CI_COMMIT_TAG | sed -E 's/^([a-z._-]+)@.*/\1/')
    - turbo prune --scope=$APP_NAME --out-dir out --docker
  artifacts:
    expire_in: 1 hour
    paths:
      - out/

.merge-request-summarize:
  image: node:22
  stage: prepare
  variables:
    GIT_DEPTH: 0
  extends:
    - .merge-request-rules
  before_script:
    - apt update && apt install -y git
    - npm install -g turbo@^2
    - corepack enable
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install --no-frozen-lockfile
    - |
      pnpm exec merge-request-analyzer $CI_MERGE_REQUEST_DIFF_BASE_SHA \
      --branch $CI_MERGE_REQUEST_TARGET_BRANCH_NAME \
      > merge-request.summary.json
  artifacts:
    paths:
      - merge-request.summary.json
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

# TODO: Migrate this job to use `changesets`
release-devops-packages:
  image: node:22
  stage: release
  extends:
    - .devops-rules
  script:
    - apt update && apt install -y jq
    - corepack enable
    - npm install -g turbo@^2
    # Authenticate
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "${CI_API_V4_URL#http*:}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}" >> .npmrc
    # Extract version segment from tag
    - export TAG_VERSION=${CI_COMMIT_TAG:7}
    # Publish devops packages
    - ./scripts/publish-package @eliarelektronik/samba-env $TAG_VERSION

release-apps:
  stage: release
  tags: [docker]
  extends:
    - .app-rules
  # Required variables (defined in GitLab CI/CD Settings)
  # - SMTP_CONF: ssmtp configuration to send warning e-mails (https://linux.die.net/man/5/ssmtp.conf)
  # - SMTP_FROM: mail author name <email>
  # - SMTP_TO: comma seperated e-mail addresses
  # - TURBO_CONFIG: Turbo cache configuration
  # - TURBO_FORCE: Ignore turbo cache
  # - TURBO_TOKEN: Auth token for turbo cache
  before_script:
    - apk add --no-cache jq ssmtp gomplate
    - *docker-prepare
  script:
    - mkdir release-logs
    - export ERRORS=""
    # Build/Push every app defined in TARGET_APPS sequentially
    - |
      for APP_NAME in $TARGET_APPS; do
        LOG_PATH="release-logs/$APP_NAME.log"
        ERR_PATH="release-logs/$APP_NAME.error.log"
        EXIT_CODE=0

        # Variables for docker bake
        export APP_NAME="$APP_NAME"
        export APP_ROLES="$(jq -Mc '.roles // []' "apps/$APP_NAME/manifest.json" 2> /dev/null || echo '[]')"

        rm -rf out && mv out-$APP_NAME out
        # Output build logs to both the console and a log file
        {
          docker buildx bake "$APP_NAME" --push 2>&1 || {
            mv $LOG_PATH $ERR_PATH
          }
        } | tee $LOG_PATH

        if [ -e "$ERR_PATH" ]; then
          if [ -n "$ERRORS" ]; then
            ERRORS="$ERRORS,$APP_NAME"
          else
            ERRORS="$APP_NAME"
          fi
        fi
      done
    # Send mail with list of failed apps, TODO: attach logs to mail
    - |
      if [ -n "$ERRORS" ]; then
          ssmtp -C"$SMTP_CONF" "$SMTP_TO" <<EOF
      From: $SMTP_FROM
      To: $SMTP_TO
      Subject: $CI_PROJECT_NAME | Pipeline Warning | $CI_COMMIT_SHORT_SHA
      Content-Type: text/html; charset=UTF-8

      <html>
        <body>
          <p>Build failed for following apps: </p>
          <ul>
            $(gomplate -i '{{range strings.Split "," .Env.ERRORS}}<li>{{.}}</li>{{end}}')
          </ul>
          <p>Pipeline: <a href="$CI_PROJECT_URL/-/pipelines/$CI_PIPELINE_ID">#$CI_PIPELINE_ID</a></p>
        </body>
      </html>
      EOF
          exit 1
      fi;
  # Ideally, the job script should only fail on the last line.
  # If the script exits at that stage, we still want to proceed to the deployment stage with what has already been built.
  # This is a temporary solution to avoid rebuilding all of the apps if a few of them fail.
  # In the future, each app should be built based on the changed files since its last valid version tag.
  allow_failure: true
  artifacts:
    name: $CI_COMMIT_TAG-$CI_PIPELINE_ID
    when: always
    paths:
      - release-logs/

release-hotfix:
  stage: release
  tags: [docker]
  extends:
    - .hotfix-rules
  before_script:
    - apk add --no-cache jq
    - *docker-prepare
  script:
    - mkdir release-logs
    - export ERRORS=""
    - export APP_NAME=$(echo $CI_COMMIT_TAG | sed -E 's/^([a-z._-]+)@.*/\1/')
    # Variables for docker bake
    - export APP_ROLES="$(jq -Mc '.roles // []' "apps/$APP_NAME/manifest.json" 2> /dev/null || echo '[]')"
    # Output build logs to both the console and a log file
    - |
      {
        docker buildx bake "$APP_NAME" --push 2>&1 || {
          mv "release-logs/$APP_NAME.log" "release-logs/$APP_NAME.error.log"
          exit 1
        }
      } | tee "release-logs/$APP_NAME.log"
  artifacts:
    name: $CI_COMMIT_TAG-$CI_PIPELINE_ID
    when: always
    paths:
      - release-logs/

.deploy:
  image: ubuntu:22.04
  stage: deploy
  extends:
    - .app-rules
  environment: staging
  before_script:
    - *prepare-ssh
  script:
    - |
      ssh eliar@$STAGING_HOST <<EOF
      cd $STAGING_PROJECT_DIR;
      ./compose-environment staging pull;
      ./compose-environment staging up -d;
      ./compose-environment testing up -d;
      EOF
