stages:
  - prepare
  - release

.apps: &apps
  - dispensing-manager-ui
  - machines
  - multi-monitor
  - root
  - websockify

.docker-login: &docker-login
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

workflow:
  rules:
    - if: $CI_COMMIT_TAG == "staging"

prepare:
  image: node:18
  stage: prepare
  parallel:
    matrix:
      - APP_NAME: *apps
  script:
    - npm install -g turbo
    - npx turbo prune --scope=$APP_NAME --out-dir out-$APP_NAME --docker
  artifacts:
    paths:
      - out-$APP_NAME/

release:
  stage: release
  tags: [docker]
  parallel:
    matrix:
      - APP_NAME: *apps
  variables:
    NPM_TOKEN: $CI_JOB_TOKEN
    TURBO_TOKEN: $TURBO_TOKEN
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$APP_NAME:$CI_COMMIT_TAG
    IMAGE_SHA: $CI_REGISTRY_IMAGE/$APP_NAME:$CI_COMMIT_SHA
    IMAGE_LATEST: $CI_REGISTRY_IMAGE/$APP_NAME:latest
    PKG_PATH: apps/$APP_NAME/package.json
  before_script:
    - apt-get update && apt-get install jq
  script:
    - mv out-$APP_NAME out
    - *docker-login
    - docker build
      --cache-from $IMAGE_LATEST
      --build-arg APP_NAME="$APP_NAME"
      --build-arg APP_VERSION="$IMAGE_TAG"
      --build-arg APP_PORT=$(jq .eliar.port $PKG_PATH)
      --build-arg APP_OUT_DIR=$(jq .eliar.outDir $PKG_PATH)
      --build-arg TURBO_CONFIG="$TURBO_CONFIG"
      --secret id=NPM_TOKEN
      --secret id=TURBO_TOKEN
      -t $IMAGE_TAG -t $IMAGE_SHA .
    - docker push $IMAGE_TAG
    - docker push $IMAGE_SHA
