stages:
  - prepare
  - release
  - deploy

.docker-login: &docker-login
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.prepare-ssh: &prepare-ssh
  # Install ssh-agent
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  # Run ssh-agent
  - eval $(ssh-agent -s)
  # # Give the right permissions, otherwise ssh-add will refuse to add files
  # # Add the SSH key stored in SSH_PRIVATE_KEY file type CI/CD variable to the agent store
  - chmod 400 "$SSH_PRIVATE_KEY"
  - ssh-add "$SSH_PRIVATE_KEY"
  # # Create the SSH directory and give it the right permissions
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # # Copy known hosts file to SSH directory
  - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

.app-rules:
  rules:
    - if: $CI_COMMIT_TAG == "staging"
    - if: $CI_COMMIT_TAG =~ /^v/

.devops-rules:
  rules:
    - if: $CI_COMMIT_TAG =~ /^devops@/

workflow:
  rules:
    - if: $CI_COMMIT_TAG

variables:
  TARGET_APPS:
    value: dispensing-manager-ui dispensing-management-systems machine-status machines multi-monitor planning-board planning-board-engine root websockify
    description: Whitespace seperated list of apps to build/release

prepare-apps:
  image: node:20
  stage: prepare
  extends:
    - .app-rules
  script:
    - npm install -g turbo
    - |
      for APP_NAME in $TARGET_APPS; do
        turbo prune --scope=$APP_NAME --out-dir out-$APP_NAME --docker
      done
  artifacts:
    paths:
      - out-*/

# TODO: Migrate this job to use `changesets`
release-devops-packages:
  image: node:20
  stage: release
  extends:
    - .devops-rules
  script:
    - apt update && apt-get install jq
    - corepack enable
    - npm install -g turbo
    # Authenticate
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    # Extract version segment from tag
    - export VERSION=${CI_COMMIT_TAG:7}
    # Publish all devops packages
    - |
      pnpm list --filter './devops/*' -r --depth -1 --json | jq -Mrc .[] | while read -r PKG; do
        OUT_DIR=out
        PKG_NAME=$(echo $PKG | jq -Mr .name)
        PKG_BASENAME=$(basename "$(echo $PKG | jq -Mr .path)")
        PKG_VERSION=$(echo $PKG | jq -Mr .version)
        PKG_BUILD_PATH=$OUT_DIR/devops/$PKG_BASENAME

        turbo prune --scope=$PKG_NAME --out-dir $OUT_DIR
        pnpm install -C $OUT_DIR
        pnpm run -C $OUT_DIR build
        if [[ $PKG_VERSION != $VERSION ]]; then
          echo ""
          echo "Version of package '$PKG_NAME' does not match given tag name."
          echo "Tag version: $VERSION, Package Version: $PKG_VERSION"
          echo ""
          tmp=$(mktemp)
          jq --arg version "$VERSION" '.version = $version' $PKG_BUILD_PATH/package.json > "$tmp"
          mv "$tmp" $PKG_BUILD_PATH/package.json
        fi
        pnpm publish $PKG_BUILD_PATH
      done

release-apps:
  stage: release
  tags: [docker]
  extends:
    - .app-rules
  variables:
    NPM_TOKEN: $CI_JOB_TOKEN
    TURBO_TOKEN: $TURBO_TOKEN
  before_script:
    - apk add --no-cache jq
    - *docker-login
  script:
    - mkdir release-logs
    - |
      for APP_NAME in $TARGET_APPS; do
        LOG_PATH="release-logs/$APP_NAME.log"
        ERR_PATH="release-logs/$APP_NAME.error.log"
        rm -rf out && mv out-$APP_NAME out
        {
          ./scripts/release.sh $APP_NAME 2>&1 || {
            export CI_ERROR=1
            mv $LOG_PATH $ERR_PATH
          }
        } | tee $LOG_PATH
      done
      if [ -n "$CI_ERROR" ]; then exit 1; fi;
  artifacts:
    name: $CI_COMMIT_TAG-$CI_PIPELINE_ID
    when: always
    paths:
      - release-logs/

deploy:
  image: ubuntu:22.04
  stage: deploy
  extends:
    - .app-rules
  environment: staging
  before_script:
    - *prepare-ssh
  script:
    - ssh eliar@$STAGING_HOST "docker compose --project-directory $STAGING_PROJECT_DIR pull"
    - ssh eliar@$STAGING_HOST "docker compose --project-directory $STAGING_PROJECT_DIR up -d"
