/*
SELECT NAME, PARAMSTRING FROM BFCOMMANDPARAMETERS
LEFT JOIN BFMACHINES ON BFMACHINES.MACHINEID = BFCOMMANDPARAMETERS.MACHINEID
LEFT JOIN BFMASTERCOMMANDS ON BFMASTERCOMMANDS.COMMANDNO = BFCOMMANDPARAMETERS.COMMANDNO and
BFMASTERCOMMANDS.MACHINEID = BFCOMMANDPARAMETERS.MACHINEID
AND BFMACHINES.MACHINEID = BFMASTERCOMMANDS.MACHINEID
LEFT JOIN BFTREATMENTPARAMETERGROUPMACHINES ON BFTREATMENTPARAMETERGROUPMACHINES.MACHINEID = BFCOMMANDPARAMETERS.MACHINEID
LEFT JOIN BFTREATMENTPARAMETERGROUPS ON BFTREATMENTPARAMETERGROUPS.ID = BFTREATMENTPARAMETERGROUPMACHINES.GROUPID
WHERE BFCOMMANDPARAMETERS.PROGRAMEDITING = 1
and BFTREATMENTPARAMETERGROUPS.ID = 1
*/

import { knex } from '~/server/connectionPool'

export default defineEventHandler(async (event) => {
  const { id } = await readBody(event)

  const { machineId } = await knex('BFTREATMENTPARAMETERGROUPMACHINES')
    .leftJoin('BFMACHINES', 'BFMACHINES.MACHINEID', 'BFTREATMENTPARAMETERGROUPMACHINES.MACHINEID')
    .where('GROUPID', id)
    .select({
      machineId: 'BFTREATMENTPARAMETERGROUPMACHINES.MACHINEID',
    }).first()

  // parameter id
  return await knex.raw(`
  Select cmd.COMMANDNO, cmd.NAME, prm.PARAMETERINDEX, prm.PARAMSTRING From BFCOMMANDPARAMETERS prm
   LEFT JOIN BFMASTERCOMMANDS cmd
   ON prm.MACHINEID = cmd.MACHINEID AND prm.COMMANDNO = cmd.COMMANDNO
   WHERE prm.MACHINEID = (?) AND prm.USEDEFAULT = 0
  `, [machineId])
})
