/*
SELECT NAME, PARAMSTRING FROM BFCOMMANDPARAMETERS
LEFT JOIN BFMACHINES ON BFMACHINES.MACHINEID = BFCOMMANDPARAMETERS.MACHINEID
LEFT JOIN BFMASTERCOMMANDS ON BFMASTERCOMMANDS.COMMANDNO = BFCOMMANDPARAMETERS.COMMANDNO and
BFMASTERCOMMANDS.MACHINEID = BFCOMMANDPARAMETERS.MACHINEID
AND BFMACHINES.MACHINEID = BFMASTERCOMMANDS.MACHINEID
LEFT JOIN BFTREATMENTPARAMETERGROUPMACHINES ON BFTREATMENTPARAMETERGROUPMACHINES.MACHINEID = BFCOMMANDPARAMETERS.MACHINEID
LEFT JOIN BFTREATMENTPARAMETERGROUPS ON BFTREATMENTPARAMETERGROUPS.ID = BFTREATMENTPARAMETERGROUPMACHINES.GROUPID
WHERE BFCOMMANDPARAMETERS.PROGRAMEDITING = 1
and BFTREATMENTPARAMETERGROUPS.ID = 1
*/

import { knex } from '~/server/connectionPool'

export default defineEventHandler(async (event) => {
  const { id } = await readBody(event)
  return await knex.raw(`SELECT NAME, PARAMSTRING FROM BFCOMMANDPARAMETERS
  LEFT JOIN BFMACHINES ON BFMACHINES.MACHINEID = BFCOMMANDPARAMETERS.MACHINEID
  LEFT JOIN BFMASTERCOMMANDS ON BFMASTERCOMMANDS.COMMANDNO = BFCOMMANDPARAMETERS.COMMANDNO and
  BFMASTERCOMMANDS.MACHINEID = BFCOMMANDPARAMETERS.MACHINEID
  AND BFMACHINES.MACHINEID = BFMASTERCOMMANDS.MACHINEID
  LEFT JOIN BFTREATMENTPARAMETERGROUPMACHINES ON BFTREATMENTPARAMETERGROUPMACHINES.MACHINEID = BFCOMMANDPARAMETERS.MACHINEID
  LEFT JOIN BFTREATMENTPARAMETERGROUPS ON BFTREATMENTPARAMETERGROUPS.ID = BFTREATMENTPARAMETERGROUPMACHINES.GROUPID
  WHERE BFCOMMANDPARAMETERS.PROGRAMEDITING = 1
  and BFTREATMENTPARAMETERGROUPS.ID = ${id}`)
})
