keycloak:
  url: http://localhost:8080/auth
  user: user
  password: 123456
  defaultLocale: en

clients:
  - id: dispensing-management-systems
    path: /
    public: true

users:
  - username: onur
    firstName: Onur
    lastName: Enginer
    password: 12345
    email: onur.enginer@eliarge.com
    locale: tr
  - username: admin
    firstName: Admin
    lastName: User
    password: admin
    email: admin@admin.com
    locale: en
    #Eliar3542784!
