-- OTR_BA_COMMANDIO_SELECTIONLIST source
IF OBJECT_ID('OTR_BA_COMMANDIO_SELECTIONLIST','V') IS NULL
BEGIN
    EXEC('
    CREATE VIEW [dbo].[OTR_BA_COMMANDIO_SELECTIONLIST]
    AS
    SELECT     BACOMMANDINPUTOUTPUTS.IOINDEX, BACOMMANDINPUTOUTPUTS.MACHINECOMMANDSETNO,
                          BACOMMANDINPUTOUTPUTS.MACHINEID, BACOMMANDINPUTOUTPUTS.COMMANDNO, BACOMMANDINPUTOUTPUTS.IOID AS IO_IOID,
                          BACOMMANDINPUTOUTPUTS.IOTYPE AS IO_IOTYPE, BACOMMANDINPUTOUTPUTS.NAME AS IO_NAME,
                          BACOMMANDSELECTIONLIST.SELECTINDEX, BACOMMANDSELECTIONLIST.IOTYPE AS SELECTEDIOTYPE,
                          BACOMMANDSELECTIONLIST.SELECTEDIOID, BACOMMANDSELECTIONLIST.NAME AS SELECTEDNAME,
                          BACOMMANDSELECTIONLIST.ISDEFAULT
    FROM         BACOMMANDINPUTOUTPUTS LEFT OUTER JOIN
                          BACOMMANDSELECTIONLIST ON
                          BACOMMANDINPUTOUTPUTS.MACHINECOMMANDSETNO = BACOMMANDSELECTIONLIST.MACHINECOMMANDSETNO AND
                          BACOMMANDINPUTOUTPUTS.IOINDEX = BACOMMANDSELECTIONLIST.IOINDEX AND
                          BACOMMANDINPUTOUTPUTS.COMMANDNO = BACOMMANDSELECTIONLIST.COMMANDNO AND
                          BACOMMANDINPUTOUTPUTS.MACHINEID = BACOMMANDSELECTIONLIST.MACHINEID;
    ');
END;

-- OTR_BA_COMMAND_COMMANDPARAMS source
IF OBJECT_ID('OTR_BA_COMMAND_COMMANDPARAMS','V') IS NULL
BEGIN
    EXEC('
    CREATE VIEW [dbo].[OTR_BA_COMMAND_COMMANDPARAMS]
    AS
    SELECT     BAMASTERCOMMANDS.MACHINEID, BAMASTERCOMMANDS.MACHINECOMMANDSETNO, BAMASTERCOMMANDS.COMMANDNO,
                          BAMASTERCOMMANDS.ACTIVATED, BAMASTERCOMMANDS.NAME,
                          BAMASTERCOMMANDS.FUNCTIONID, BAMASTERCOMMANDS.TBBFUNTIONNAME, BAMASTERCOMMANDS.ICON,
                          BAMASTERCOMMANDS.ADVICELIST, BAMASTERCOMMANDS.DONTUSELIST, BAMASTERCOMMANDS.ISRUNMANUAL,
                          BAMASTERCOMMANDS.COMMANDTYPE, BAMASTERCOMMANDS.MOVEPARALLEL, BAMASTERCOMMANDS.TBBCHANGETIME,
                          BAMASTERCOMMANDS.X, BAMASTERCOMMANDS.Y, BAMASTERCOMMANDS.A, BAMASTERCOMMANDS.B,
                          BAMASTERCOMMANDS.MAXA, BAMASTERCOMMANDS.ISTEMPERATURE, BAMASTERCOMMANDS.ISUNLOAD,
                          BACOMMANDPARAMETERS.PARAMETERINDEX, BACOMMANDPARAMETERS.PARAMSTRING, BACOMMANDPARAMETERS.[VALUE],
                          BACOMMANDPARAMETERS.PARAMETERTYPE, BACOMMANDPARAMETERS.SELECTIONLIST,
                          BACOMMANDPARAMETERS.SELECTIONVALUES, BACOMMANDPARAMETERS.UNITCODE, BACOMMANDPARAMETERS.PARAMLOWLIMIT,
                          BACOMMANDPARAMETERS.PARAMHIGHLIMIT, BACOMMANDPARAMETERS.CONTAINSVARIABLE,
                          BACOMMANDPARAMETERS.TEMPERATURE, BACOMMANDPARAMETERS.USEDEFAULT,
                          BACOMMANDPARAMETERS.ISCOMMANDVARIABLE, BACOMMANDPARAMETERS.TBBFORMUL
    FROM         BAMASTERCOMMANDS LEFT OUTER JOIN
                          BACOMMANDPARAMETERS ON BAMASTERCOMMANDS.MACHINEID = BACOMMANDPARAMETERS.MACHINEID AND
                          BAMASTERCOMMANDS.MACHINECOMMANDSETNO = BACOMMANDPARAMETERS.MACHINECOMMANDSETNO AND
                          BAMASTERCOMMANDS.COMMANDNO = BACOMMANDPARAMETERS.COMMANDNO;
    ');
END;

-- OTR_BA_STEPIO_SELECTIONLIST source
IF OBJECT_ID('OTR_BA_STEPIO_SELECTIONLIST','V') IS NULL
BEGIN
    EXEC('
    CREATE VIEW [dbo].[OTR_BA_STEPIO_SELECTIONLIST]
    AS
    SELECT     BAMASTERSTEPINPUTOUTPUTS.IOINDEX, BAMASTERSTEPINPUTOUTPUTS.MACHINEID,
                          BAMASTERSTEPINPUTOUTPUTS.MACHINEPRGVERSIONNO, BAMASTERSTEPINPUTOUTPUTS.MAINSTEP,
                          BAMASTERSTEPINPUTOUTPUTS.PARALELSTEP, BAMASTERSTEPINPUTOUTPUTS.PROGNO, BAMASTERSTEPINPUTOUTPUTS.IOID,
                          BAMASTERSTEPINPUTOUTPUTS.IOTYPE, BAMASTERSTEPSELECTIONLIST.SELECTEDIOID,
                          BAMASTERSTEPSELECTIONLIST.SELECTIONINDEX, BAMASTERSTEPSELECTIONLIST.IOTYPE AS SELECTEDIOTYPE
    FROM         BAMASTERSTEPINPUTOUTPUTS LEFT OUTER JOIN
                          BAMASTERSTEPSELECTIONLIST ON BAMASTERSTEPINPUTOUTPUTS.IOINDEX = BAMASTERSTEPSELECTIONLIST.IOINDEX AND
                          BAMASTERSTEPINPUTOUTPUTS.MACHINEID = BAMASTERSTEPSELECTIONLIST.MACHINEID AND
                          BAMASTERSTEPINPUTOUTPUTS.MACHINEPRGVERSIONNO = BAMASTERSTEPSELECTIONLIST.MACHINEPRGVERSIONNO AND
                          BAMASTERSTEPINPUTOUTPUTS.MAINSTEP = BAMASTERSTEPSELECTIONLIST.MAINSTEP AND
                          BAMASTERSTEPINPUTOUTPUTS.PARALELSTEP = BAMASTERSTEPSELECTIONLIST.PARALELSTEP AND
                          BAMASTERSTEPINPUTOUTPUTS.PROGNO = BAMASTERSTEPSELECTIONLIST.PROGNO;
    ');
END;

-- OTR_BA_STEP_STEPPARAMS source
IF OBJECT_ID('OTR_BA_STEP_STEPPARAMS','V') IS NULL
BEGIN
    EXEC('
    CREATE VIEW [dbo].[OTR_BA_STEP_STEPPARAMS]
    AS
    SELECT     BAMASTERSTEPS.MACHINEID, BAMASTERSTEPS.MACHINEPRGVERSIONNO,
                          BAMASTERSTEPS.PROGNO, BAMASTERSTEPS.MAINSTEP, BAMASTERSTEPS.PARALELSTEP,
                          BAMASTERSTEPS.COMMANDNO, BAMASTERSTEPS.ISCONDITIONAL, BAMASTERSTEPS.CONDITIONSTR,
                          BAMASTERSTEPPARAMS.PARAMETERINDEX, BAMASTERSTEPPARAMS.VALUE, BAMASTERSTEPPARAMS.CONTAINSVARIABLE
    FROM         BAMASTERSTEPS
                          LEFT OUTER JOIN
                          BAMASTERSTEPPARAMS ON BAMASTERSTEPS.MACHINEID = BAMASTERSTEPPARAMS.MACHINEID AND
                          BAMASTERSTEPS.PROGNO = BAMASTERSTEPPARAMS.PROGNO AND
                          BAMASTERSTEPS.MACHINEPRGVERSIONNO = BAMASTERSTEPPARAMS.MACHINEPRGVERSIONNO AND
                          BAMASTERSTEPS.MAINSTEP = BAMASTERSTEPPARAMS.MAINSTEP AND
                          BAMASTERSTEPS.PARALELSTEP = BAMASTERSTEPPARAMS.PARALELSTEP;
    ');
END;

-- OTR_COMMANDIO_SELECTIONLIST source
IF OBJECT_ID('OTR_COMMANDIO_SELECTIONLIST','V') IS NULL
BEGIN
    EXEC('
    CREATE VIEW [dbo].[OTR_COMMANDIO_SELECTIONLIST]
    AS
    SELECT     BFCOMMANDINPUTOUTPUTS.IOINDEX, BFCOMMANDINPUTOUTPUTS.MACHINEID, BFCOMMANDINPUTOUTPUTS.COMMANDNO,
                          BFCOMMANDINPUTOUTPUTS.IOID AS IO_IOID, BFCOMMANDINPUTOUTPUTS.IOTYPE AS IO_IOTYPE,
                          BFCOMMANDINPUTOUTPUTS.NAME AS IO_NAME, BFCOMMANDINPUTOUTPUTS.PROGRAMEDITING,
                          BFCOMMANDINPUTOUTPUTS.COMMANDRUN, BFCOMMANDSELECTIONLIST.SELECTINDEX,
                          BFCOMMANDSELECTIONLIST.IOTYPE AS SELECTEDIOTYPE, BFCOMMANDSELECTIONLIST.SELECTEDIOID,
                          BFCOMMANDSELECTIONLIST.NAME AS SELECTEDNAME, BFCOMMANDSELECTIONLIST.ISDEFAULT,
                          BFCOMMANDSELECTIONLIST.MODEL, BFCOMMANDSELECTIONLIST.EXTENTION
    FROM         BFCOMMANDINPUTOUTPUTS LEFT OUTER JOIN
                          BFCOMMANDSELECTIONLIST ON BFCOMMANDINPUTOUTPUTS.IOINDEX = BFCOMMANDSELECTIONLIST.IOINDEX AND
                          BFCOMMANDINPUTOUTPUTS.COMMANDNO = BFCOMMANDSELECTIONLIST.COMMANDNO AND
                          BFCOMMANDINPUTOUTPUTS.MACHINEID = BFCOMMANDSELECTIONLIST.MACHINEID;
    ');
END;

-- OTR_COMMAND_COMMANDPARAMS source
IF OBJECT_ID('OTR_COMMAND_COMMANDPARAMS','V') IS NULL
BEGIN
    EXEC('
    CREATE VIEW [dbo].[OTR_COMMAND_COMMANDPARAMS]
    AS
    SELECT     BFMASTERCOMMANDS.MACHINEID, BFMASTERCOMMANDS.COMMANDNO, BFMASTERCOMMANDS.ACTIVATED,
                          BFMASTERCOMMANDS.NAME, BFMASTERCOMMANDS.FUNCTIONID,
                          BFMASTERCOMMANDS.TBBFUNTIONNAME, BFMASTERCOMMANDS.ICON, BFMASTERCOMMANDS.ADVICELIST,
                          BFMASTERCOMMANDS.DONTUSELIST, BFMASTERCOMMANDS.ISRUNMANUAL, BFMASTERCOMMANDS.COMMANDTYPE,
                          BFMASTERCOMMANDS.MOVEPARALLEL, BFMASTERCOMMANDS.TBBCHANGETIME, BFMASTERCOMMANDS.X,
                          BFMASTERCOMMANDS.Y, BFMASTERCOMMANDS.A, BFMASTERCOMMANDS.B, BFMASTERCOMMANDS.MAXA,
                          BFMASTERCOMMANDS.ISTEMPERATURE, BFMASTERCOMMANDS.ISUNLOAD, BFCOMMANDPARAMETERS.PARAMETERINDEX,
                          BFCOMMANDPARAMETERS.PARAMSTRING, BFCOMMANDPARAMETERS.[VALUE], BFCOMMANDPARAMETERS.PARAMETERTYPE,
                          BFCOMMANDPARAMETERS.SELECTIONLIST, BFCOMMANDPARAMETERS.SELECTIONVALUES, BFCOMMANDPARAMETERS.UNITCODE,
                          BFCOMMANDPARAMETERS.PARAMLOWLIMIT, BFCOMMANDPARAMETERS.PARAMHIGHLIMIT,
                          BFCOMMANDPARAMETERS.CONTAINSVARIABLE, BFCOMMANDPARAMETERS.TEMPERATURE,
                          BFCOMMANDPARAMETERS.USEDEFAULT, BFCOMMANDPARAMETERS.ISCOMMANDVARIABLE,
                          BFCOMMANDPARAMETERS.TBBFORMUL, BFMASTERCOMMANDS.ISDELETED, BFMASTERCOMMANDS.ISCHANGED
    FROM         BFMASTERCOMMANDS LEFT OUTER JOIN
                          BFCOMMANDPARAMETERS ON BFMASTERCOMMANDS.MACHINEID = BFCOMMANDPARAMETERS.MACHINEID AND
                          BFMASTERCOMMANDS.COMMANDNO = BFCOMMANDPARAMETERS.COMMANDNO;
    ');
END;

-- OTR_DYB_BATCH_ORDER_RECIPE source
IF OBJECT_ID('OTR_DYB_BATCH_ORDER_RECIPE','V') IS NULL
BEGIN
    EXEC('
    CREATE VIEW [dbo].[OTR_DYB_BATCH_ORDER_RECIPE] AS
    SELECT NULL AutoKey, PLANKEY, JOBORDER, RCPINDEX, DYEREQUESTNUMBER, MAINSTEP, PARALLELSTEP, RECIPETYPE, CHEMCODE, AMOUNT, AMOUNDUNIT, FINISHED, REQNO_BATCH, REQNO_PROG, otherUnit, NULL CallOffManuel, NULL RECIPENO, ''AUTO'' AS TYPE
    FROM DYBFBATCHORDERRECIPESTEPS
    UNION ALL
    SELECT AutoKey, PLANKEY, JOBORDER, RCPINDEX, DYEREQUESTNUMBER, MAINSTEP, PARALLELSTEP, RECIPETYPE, CHEMCODE, AMOUNT, AMOUNDUNIT, NULL FINISHED, REQNO_BATCH, REQNO_PROG, otherUnit, CallOffManuel, RECIPENO, ''MANUAL'' AS TYPE
    FROM DYBFBATCHORDERRECIPEMANUALS;
    ');
END;

