#!/bin/sh
# This script:
#  - assumes `jq` is installed
#  - assumes 'out' directory to contain the build output
#  - expects to be run in gitlab ci environment
#  - expects to be executed at workspace root
#  - uses busybox date function

set -e

APP_NAME=$1

if [ -z "$APP_NAME" ]; then
  echo "App name is not defined"
fi

if [ ! -e "apps/$APP_NAME" ]; then
  echo "App \"$APP_NAME\" does not exist"
  exit 1
fi

if [ -z "$CI_REGISTRY_IMAGE" ]; then
  echo "Should be run via gitlab-ci"
  exit 1
fi

if ! jq -e .scripts.start apps/$APP_NAME/package.json > /dev/null; then
  echo "Start script missing from 'package.json'"
  exit 1
fi

app_type() {
  local app_name=$1
  if ls ./apps/$app_name | grep -qE "^nuxt\.config\.(m?j|t)s$"; then
    echo "nuxt"
  else
    echo "node"
  fi
}

BUILD_DATE=$(date -u -Iseconds)
PKG_PATH=apps/$APP_NAME/package.json
MANIFEST_PATH=apps/$APP_NAME/manifest.json

IMAGE_TAG=$CI_REGISTRY_IMAGE/$APP_NAME:$CI_COMMIT_TAG
IMAGE_SHA=$CI_REGISTRY_IMAGE/$APP_NAME:$CI_COMMIT_SHA
IMAGE_LATEST=$CI_REGISTRY_IMAGE/$APP_NAME:latest

echo "Building $APP_NAME"

docker pull $IMAGE_LATEST || true
docker build \
  --target $(app_type $APP_NAME) \
  --cache-from $IMAGE_LATEST \
  --build-arg APP_NAME="$APP_NAME" \
  --build-arg APP_VERSION="$CI_COMMIT_TAG" \
  --build-arg APP_COMMIT_HASH="$CI_COMMIT_SHA" \
  --build-arg APP_BUILD_DATE="$BUILD_DATE" \
  --build-arg APP_DEPENDENCIES="$(jq -r '.envDependencies | join(" ")' $MANIFEST_PATH 2> /dev/null || echo '')" \
  --build-arg TURBO_CONFIG="$TURBO_CONFIG" \
  --build-arg TURBO_FORCE="$TURBO_FORCE" \
  --label com.eliar.manifest.name="$APP_NAME" \
  --label com.eliar.manifest.version="$CI_COMMIT_TAG" \
  --label com.eliar.manifest.roles="$(jq -Mc .roles $MANIFEST_PATH 2> /dev/null || echo '[]')" \
  --label com.eliar.manifest.build.commit_hash="$CI_COMMIT_SHA" \
  --label com.eliar.manifest.build.date="$BUILD_DATE" \
  --secret id=TURBO_TOKEN \
  -t $IMAGE_TAG -t $IMAGE_SHA .

docker push $IMAGE_TAG
docker push $IMAGE_SHA

LATEST_PATTERN="^v[0-9]+\.[0-9]+\.[0-9]+$"

# If tag complies with the standard, tag it as latest
if [ $(echo $CI_COMMIT_TAG | grep -E $LATEST_PATTERN) ]; then
  docker tag $IMAGE_TAG $IMAGE_LATEST
  docker push $IMAGE_LATEST
fi
