#!/bin/sh
# This script:
#  - expects to be executed at workspace root
#  - assumes turbo package is installed globally and is the latest version https://github.com/vercel/turbo

set -e

build_image() {
  APP_NAME=$1

  if [ -z "$APP_NAME" ]; then
    echo "App name is not defined"
  fi

  if [ ! -e "apps/$APP_NAME" ]; then
    echo "App \"$APP_NAME\" does not exist"
    exit 1
  fi
  CI_COMMIT_TAG=local
  CI_COMMIT_SHA=local
  CI_REGISTRY_IMAGE=registry.gitlab.com/eliarelektronik/dijital_boyahane/teleskop-web

  IMAGE_TAG=$CI_REGISTRY_IMAGE/$APP_NAME:$CI_COMMIT_TAG
  IMAGE_SHA=$CI_REGISTRY_IMAGE/$APP_NAME:$CI_COMMIT_SHA
  IMAGE_LATEST=$CI_REGISTRY_IMAGE/$APP_NAME:latest

  BUILD_DATE=$(date -u -Iseconds)
  PKG_PATH=apps/$APP_NAME/package.json
  MANIFEST_PATH=apps/$APP_NAME/manifest.json

  echo "Building $APP_NAME"

  docker pull $IMAGE_LATEST || true
  docker build \
    --cache-from $IMAGE_LATEST \
    --build-arg APP_NAME="$APP_NAME" \
    --build-arg APP_VERSION="$CI_COMMIT_TAG" \
    --build-arg APP_COMMIT_HASH="$CI_COMMIT_SHA" \
    --build-arg APP_BUILD_DATE="$BUILD_DATE" \
    --build-arg APP_PORT="$(jq -r .eliar.port $PKG_PATH)" \
    --build-arg APP_OUT_DIR="$(jq -r .eliar.outDir $PKG_PATH)" \
    --build-arg APP_DEPENDENCIES="$(jq -r '.envDependencies | join(" ")' $MANIFEST_PATH 2> /dev/null || echo '')" \
    --label com.eliar.manifest.name="$APP_NAME" \
    --label com.eliar.manifest.version="$CI_COMMIT_TAG" \
    --label com.eliar.manifest.roles="$(jq -Mc .roles $MANIFEST_PATH 2> /dev/null || echo '[]')" \
    --label com.eliar.manifest.build.commit_hash="$CI_COMMIT_SHA" \
    --label com.eliar.manifest.build.date="$BUILD_DATE" \
    --secret id=TURBO_TOKEN \
    -t $IMAGE_TAG -t $IMAGE_SHA .
}

build_all() {
  TARGET_APPS="dispensing-manager-ui dispensing-management-systems machine-status machines multi-monitor planning-board planning-board-engine root websockify program-editor"

  rm -rf release-logs
  mkdir -p release-logs

  for APP_NAME in $TARGET_APPS; do
    LOG_PATH="release-logs/$APP_NAME.log"
    ERR_PATH="release-logs/$APP_NAME.error.log"

    rm -rf out
    turbo prune --scope=$APP_NAME --docker
    {
      build_image $APP_NAME 2>&1 || {
        export CI_ERROR=1
        mv $LOG_PATH $ERR_PATH
      }
    } | tee $LOG_PATH
  done
}

build_all


